# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1c30b4dd320ad2dd9b294e3689e025d61f3cbe2e099c00146ac6e3a59123be49852d571b80a1afb14fb8872ddf1b1bad8d9184b009f360aaeadadc1a95feb89d

test:
  secret_key_base: 7c8bc9658ba21305546c37c910660dd2c1771fc3a43a7e2447e5c6b7ee4cb053c80bdba6ce9525d566e49e88424aedaf2f1d441b1c10ee7678e311c61b04b64e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
